######### NORMAL OPERATION  ###########

@baseUrl = http://localhost:3000/auths

### Register a User
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "newUser",
    "password": "Password123",
    "birthdate": "2000-01-01"
}

### Login a User
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "newUser",
    "password": "Password123"
}

### WRONG OPERATION

### Register a User 
### Should fail because birthdate is missing
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "userWithoutBirthdate",
    "password": "password123"
}

### Register a User 
### Should fail because newUser is already taken

POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "newUser",
    "password": "Password123",
    "birthdate": "2000-01-01"
}

### Register a User 
### Should fail because password isn't strong enough 

POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "newUser",
    "password": "password123",
    "birthdate": "2000-01-01"
}

### Login with Wrong Credentials
### Should fail because password is wrong
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "newUser",
    "password": "Password1234"
}
