######### NORMAL OPERATION  ###########

@baseUrl = http://localhost:3000/users
@username = Max
@skinName = skin1
@skinNumber = 1
@starsToAdd = 10
@newScore = 100

### Get All Users
GET {{baseUrl}}/

### Get All Skins
GET {{baseUrl}}/get-skins

### Get Current Skin of a User
GET {{baseUrl}}/current-skin/{{username}}

### Get Balance of a User
GET {{baseUrl}}/get-balance/{{username}}

### Update Score of a User
PATCH {{baseUrl}}/update-score
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjgyODgyMywiZXhwIjoxNzg5MjI4ODIzfQ.gB6rxyC_a4ubeUNIJTYCnFCpXY-QrIlixMb0Dbog_Ps
Content-Type: application/json

{
    "newScore": {{newScore}}
}

### Add Stars to a User
PATCH {{baseUrl}}/add-stars
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjc2ODU1NywiZXhwIjoxNzg5MTY4NTU3fQ.LpBGhfd1rYNGIH7UpqOdWjtMzmO41MZD4bLsZ2qFmiM
Content-Type: application/json

{
    "stars": {{starsToAdd}}
}

### Get Users Leaderboard
GET {{baseUrl}}/classement

### Unlock a Skin for a User
PATCH {{baseUrl}}/unlock-skin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjc2ODU1NywiZXhwIjoxNzg5MTY4NTU3fQ.LpBGhfd1rYNGIH7UpqOdWjtMzmO41MZD4bLsZ2qFmiM
Content-Type: application/json

{
    "skinName": "{{skinName}}"
}

### Check if a User has a Skin
GET {{baseUrl}}/check-skin/{{username}}/{{skinName}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjc2ODU1NywiZXhwIjoxNzg5MTY4NTU3fQ.LpBGhfd1rYNGIH7UpqOdWjtMzmO41MZD4bLsZ2qFmiM


### Change Current Skin of a User
PATCH {{baseUrl}}/change-current-skin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjc2ODU1NywiZXhwIjoxNzg5MTY4NTU3fQ.LpBGhfd1rYNGIH7UpqOdWjtMzmO41MZD4bLsZ2qFmiM
Content-Type: application/json

{
    "skinNumber": {{skinNumber}}
}

### WRONG OPERATONS

### Unlock a Skin for a User
### Should fail because skin is already owned
POST {{baseUrl}}/unlock-skin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjc2ODU1NywiZXhwIjoxNzg5MTY4NTU3fQ.LpBGhfd1rYNGIH7UpqOdWjtMzmO41MZD4bLsZ2qFmiM
Content-Type: application/json

{
    "skinName": "{{skinName}}"
}

### Check if a User has a Skin
### Should fail because skin isn't owned
GET {{baseUrl}}/check-skin/{{username}}/skin5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjc2ODU1NywiZXhwIjoxNzg5MTY4NTU3fQ.LpBGhfd1rYNGIH7UpqOdWjtMzmO41MZD4bLsZ2qFmiM

