@baseUrl = http://localhost:3000

### Tyry to update a score
POST {{baseUrl}}/users/update-score
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldjIiLCJpYXQiOjE3MDI2NTQzODYsImV4cCI6MTc4OTA1NDM4Nn0.CSEwaOLaFNz6mKYAs1p68gVbbGbrxPyd8sVekEsTS-Y

{
    "newScore":10,
    "username":"kev2"
}

// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjI4OTkzOSwiZXhwIjoxNzg4Njg5OTM5fQ.1NObUWo01HtBWlGNCLBEpod-U2LAATZ51ByAtO4H8o8
### Try to update a score
POST {{baseUrl}}/users/update-score
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCIsImlhdCI6MTcwMjI4OTkzOSwiZXhwIjoxNzg4Njg5OTM5fQ.1NObUWo01HtBWlGNCLBEpod-U2LAATZ51ByAtO4H8o8
Content-Type: application/json

{
    "newScore": 10
}
###2
GET {{baseUrl}}/users/

### Unlock a skin

POST {{baseUrl}}/users/unlock-skin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldjMiLCJpYXQiOjE3MDI1NjAxMjUsImV4cCI6MTc4ODk2MDEyNX0.J9d182LTJiJV0uJmtYHKBxt-G-ZE0WBXdzMn12gLKZA
Content-Type: application/json
    
{
    "skinName": "skin5"
}

### Is Skin unlocked

GET {{baseUrl}}/users/check-skin/fff/skin4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZmZiIsImlhdCI6MTcwMjM4ODIzNywiZXhwIjoxNzg4Nzg4MjM3fQ.nKHR4p3WbIB85zMWgB0aOPt93USJmcPuTNBlTFYzApI

### Equip skin

POST {{baseUrl}}/users/change-current-skin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldjIiLCJpYXQiOjE3MDI2NTQzODYsImV4cCI6MTc4OTA1NDM4Nn0.CSEwaOLaFNz6mKYAs1p68gVbbGbrxPyd8sVekEsTS-Y

{
    "skinNumber": 4
}

### Get All skins
GET {{baseUrl}}/users/get-skins
Content-Type: application/json

### Get current skin
GET {{baseUrl}}/users/current-skin/kev3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldjMiLCJpYXQiOjE3MDI1NjAxMjUsImV4cCI6MTc4ODk2MDEyNX0.J9d182LTJiJV0uJmtYHKBxt-G-ZE0WBXdzMn12gLKZA
Content-Type: application/json 

### Get current skin
GET {{baseUrl}}/users/get-balance/kev3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldjMiLCJpYXQiOjE3MDI1NjAxMjUsImV4cCI6MTc4ODk2MDEyNX0.J9d182LTJiJV0uJmtYHKBxt-G-ZE0WBXdzMn12gLKZA
Content-Type: application/json 

### Add stars
POST {{baseUrl}}/users/add-stars
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtldjIiLCJpYXQiOjE3MDI2NTQzODYsImV4cCI6MTc4OTA1NDM4Nn0.CSEwaOLaFNz6mKYAs1p68gVbbGbrxPyd8sVekEsTS-Y
Content-Type: application/json 

{
    "stars": 10
}